### PR TITLE
Reworked README for readability

### PR DESCRIPTION
**Pull request by rhoads-zach**
@etsauer @oybed Let me know what you think.

cc: @redhat-cop/casl

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@etsauer @oybed 

I can take a pass at the other markdown files in the repo, but i wanted to get you all one example first before tackling the rest.

**Comment by logandonley** [comment]
@rhoads-zach The main README has been updated since your posting of this PR so there are now some conflicts. We like the format you've brought to the doc and would love to pull it in. 
Do you want/have time to update this PR with the content from the updated README? If not I (or someone else) can have a go at it following the formatting you've provided.

**Comment by rhoads-zach** [comment]
thank you @logandonley i'll try and take a look at it today an dammend the PR

**Comment by rhoads-zach** [comment]
@logandonley updated README to include changes from https://github.com/redhat-cop/casl-ansible/commit/a3928b40616f07046c5e749970f779af76e96da3#diff-04c6e90faac2675aa89e2176d2eec7d8

**Pull request merged**
