### PR TITLE
Role to add OpenShift container provider to CloudForms

### PR DESCRIPTION
**Pull request by sabre1041**
#### What does this PR do?
Brief explanation of the code or documentation change you've made

#### How should this be manually tested?
1. Have a CloudForms instance available
2. Use example playbook from PR substituting values as necessary

#### Is there a relevant Issue open for this?
No

#### Who would you like to review this?
cc: @redhat-cop/casl @oybed

### CODE REVIEW

**Comment by makentenza** [comment]
@sabre1041 just checked this. It works fine. A couple of comments:

-  Why don't add automatically the token from management-admin SA in management-infra namespace?
- Use FQN for Kubernetes services like kubernetes.default.svc.cluster.local and hawkular-metrics.openshift-infra.svc.cluster.local. I think is a good practice and I have seen errors in the past as Node resolver was not properly configured with domain 'search' options

**Comment by sabre1041** [comment]
@makentenza 

* Updated hostnames to include full DNS address 
* On the fence on how to utilize the token from the SA preconfigured in the cluster. Maybe only use it if another one is not provided? There may be situations where a user may create an SA for this purpose and want to use it instead. Thoughts?

**Comment by makentenza** [comment]
@sabre1041, yes, it makes sense to me as well to use the preconfigured SA from the cluster only if no one is provided. All the rest LGTM, I've tested and it worked fine.

**Comment by sabre1041** [comment]
@makentenza sounds good. I'll add in that type of functionality and follow up for another review afterward

**Comment by sabre1041** [comment]
@makentenza I added the functionality to utilize the default service account token. Please review at your convenience

**Comment by makentenza** [comment]
@sabre1041, reviewed. The functionality works fine, but please update the README.md to reflect 'ocp_token' is no longer mandatory and add some explanation as well so anyone that consume the role understands what SA is using and what are the alternatives. Apart of that is ready to merge from my point of view.

**Comment by sabre1041** [comment]
@makentenza added README content

**Comment by makentenza** [comment]
Cool @sabre1041, LGTM, but I have no permissions to merge this PR.

**Comment by oybed** [comment]
LGTM - thanks @makentenza for working with @sabre1041 on getting this reviewed / tested. Merging.

**Pull request merged**
