### PR TITLE
Ensure DNS configuration has wildcards set for infra nodes

### LINKED ISSUE #23: DNS configuration of heat based provisioning doesn't include wildcard records
It is expected that the provisioning sets up wildcard record(s) for the provisioned environment, e.g.: *.apps.example.com ==> infra node(s)

### PR DESCRIPTION
**Pull request by oybed**
#### What does this PR do?
Adds back in the wildcard for the DNS configuration

#### How should this be manually tested?
Run a provisioning following the instructions in the top level README. Check that the wildcard DNS records work afterwards (+ check the DNS config to validate that they are there)

#### Is there a relevant Issue open for this?
resolves #23

#### Who would you like to review this?
cc: @redhat-cop/casl @etsauer

### CODE REVIEW

**Comment by etsauer** [comment]
@oybed tested changs, and I do now get an apps subdomain. however, the DNS server does not get a record created for itself. This would be useful for ssh-ing into the hosts that get created. Can we make that change as part of this also?

**Comment by oybed** [comment]
@etsauer agreed - will make that change

**Comment by oybed** [comment]
@etsauer changes made to pick up all cluster hosts for DNS configuration - please review

**Comment by etsauer** [comment]
@oybed looks like there are merge conflicts now.

**Comment by oybed** [comment]
@etsauer merge conflicts fixed - you should be able to merge now.

**Pull request merged**
