### PR TITLE
Updated to handle remote execution with local inventory files

### PR DESCRIPTION
**Pull request by oybed**
#### What does this PR do?
Added functionality to copy the local files (part of the inventory) to a remote host where the `oc` commands are executed. 

#### How should this be manually tested?
Update the inventory in the tests directory to use a remote host (e.g.: an OpenShift master host) and run the test. 

#### Is there a relevant Issue open for this?
N/A

#### Who would you like to review this?
cc: @redhat-cop/casl

### CODE REVIEW

**Comment by oybed** [comment]
@etsauer Here's a proposed solution for the "remote host" - e.g.: a OpenShift master. This PR make changes to copy the local files over to the target host if the connection != 'local'. I'm not 100% happy with this solution as it slows down the execution quite a bit, but give it a try and let me know what you think about this approach.

**Comment by etsauer** [comment]
@oybed do we want to get this merged? or are we still just considering this a Work IN Progress?

**Comment by oybed** [comment]
@etsauer good to go now if you'd like to re-test/merge. 

thx

**Comment by etsauer** [comment]
@oybed getting this error now

```
TASK [openshift-applier : Apply OpenShift Cluster 'policy' - based on individual files] ***************************************************************************************************************

TASK [openshift-applier : Apply OpenShift Cluster 'policy' - based on directory] **********************************************************************************************************************
fatal: [master-0.d1.casl.rht-labs.com]: FAILED! => {"changed": true, "cmd": ["oc", "apply", "-f", "/tmp/ansible.w8pPAa//root/code/casl-ansible-inventories/d1.casl.rht-labs.com.d/inventory/../files/policy"], "delta": "0:00:00.174996", "end": "2017-09-21 13:04:12.093932", "failed": true, "rc": 1, "start": "2017-09-21 13:04:11.918936", "stderr": "error: the path \"/tmp/ansible.w8pPAa//root/code/casl-ansible-inventories/d1.casl.rht-labs.com.d/inventory/../files/policy\" does not exist", "stderr_lines": ["error: the path \"/tmp/ansible.w8pPAa//root/code/casl-ansible-inventories/d1.casl.rht-labs.com.d/inventory/../files/policy\" does not exist"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/code/casl-ansible/playbooks/openshift/post-install.retry

PLAY RECAP ********************************************************************************************************************************************************************************************
app-node-0.d1.casl.rht-labs.com : ok=2    changed=0    unreachable=0    failed=0
app-node-1.d1.casl.rht-labs.com : ok=2    changed=0    unreachable=0    failed=0
app-node-2.d1.casl.rht-labs.com : ok=2    changed=0    unreachable=0    failed=0
dns-0.d1.casl.rht-labs.com : ok=2    changed=0    unreachable=0    failed=0
infranode-0.d1.casl.rht-labs.com : ok=2    changed=0    unreachable=0    failed=0
infranode-1.d1.casl.rht-labs.com : ok=2    changed=0    unreachable=0    failed=0
master-0.d1.casl.rht-labs.com : ok=23   changed=7    unreachable=0    failed=1   
```

**Pull request merged**
