### PR TITLE
General improvemenets.

### PR DESCRIPTION
**Pull request by jtudelag**
#### What does this PR do?
Fixes Typos
Keeps MD style consistency
Adds some notes
Adds some clarifications
Adds pointers to aws docs
Adds instructions to install awscli
Adds aws handy command (Get region AZs)
Fixes delete-cluster example, did not work.

#### How should this be manually tested?
Include commands to run your new feature, and also post-run commands to validate that it worked. (please use code blocks to format code samples)

#### Is there a relevant Issue open for this?
No

#### Who would you like to review this?
cc: @redhat-cop/casl

### CODE REVIEW

**Comment by makentenza** [comment]
@jtudelag have you double checked that your PR is aligned with the existing PR on the same topic?

https://github.com/redhat-cop/casl-ansible/pull/302

**Comment by jtudelag** [comment]
> @jtudelag have you double checked that your PR is aligned with the existing PR on the same topic?
> 
> #302

Not at all,I was not aware of it ;(

**Comment by oybed** [comment]
@jtudelag @makentenza yeah, I was about to comment the same as what Mak did, so let's get #302 done first, then we can look to see if there any additional improvements to be done from there.

**Comment by oybed** [comment]
@jtudelag #302 has been merged - please refresh/rebase your PR and make additional updates if still needed (or close the PR if not).

**Comment by jtudelag** [comment]
I will, thanks for the notice @oybed.

**Comment by jtudelag** [comment]
Just changed a few things as this was already very well updated. @oybed, @makentenza  PTAL ;).

**Pull request merged**
